### ISSUE TITLE
Can't install the testsuite

### ISSUE THREAD

**Issue by Pithikos** [tavendo/AutobahnTestSuite#44]
I have a hard time trying to install the testsuite. I follow the instructions [here](http://autobahn.ws/testsuite/installation.html). I however get this error:

````
/tmp/AutobahnTestSuite/autobahntestsuite$ wstest --test
..
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite-0.6.1-py2.7.egg/autobahntestsuite/wamptestee.py", line 19, in <module>
    from autobahn.wamp1 import protocol as wamp
ImportError: No module named wamp1
````
Is there a step missing from the instructions? I tried both with `pip install` and manually with `setup.py` but I get the same errors.

**Comment by oberstet** [comment]
You are not using the latest version. Try `pip install --upgrade autobahntestsuite`
