### ISSUE TITLE
Not working with python 3.4

### ISSUE THREAD

**Issue by raoulh** [tavendo/AutobahnTestSuite#45]
I tried to install the testsuite with pip install autobahntestsuite under a python 3.4 environement and got this error when running wstest:
```
➜  ~  wstest --help
Traceback (most recent call last):
  File "/usr/bin/wstest", line 9, in <module>
    load_entry_point('autobahntestsuite==0.7.1', 'console_scripts', 'wstest')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/autobahntestsuite/__init__.py", line 22, in <module>
    import choosereactor # This MUST BE the FIRST file imported here! Do NOT touch.
ImportError: No module named 'choosereactor'
```

**Comment by oberstet** [comment]
AutobahnTestsuitebonly supports Python 2.7

**Comment by woko54** [comment]
After several attempts I was able to install wstest with Python3 pip, but now I get this when calling 'wstest -a':

Traceback (most recent call last):
  File "/home/koehn/.local/bin/wstest", line 5, in <module>
    from autobahntestsuite.wstest import run
  File "/home/koehn/.local/lib/python3.10/site-packages/autobahntestsuite/__init__.py", line 22, in <module>
    import choosereactor # This MUST BE the FIRST file imported here! Do NOT touch.
ModuleNotFoundError: No module named 'choosereactor'

If it is working only with Python 2.7 we have a vicious circle, because for installation I had to use Python 3.

**Comment by oberstet** [comment]
you can use Docker to run the testsuite to test any python version on your host: https://github.com/crossbario/autobahn-testsuite/tree/master/docker#usage

**Comment by woko54** [comment]
Would I be able to test my own Websocket Server with it ?

**Comment by oberstet** [comment]
yes

> You can use it to test WebSocket server (and client) implementations.

**Comment by oberstet** [comment]
> Thank you, I got it running with the docker-image. It is waiting for clients connecting on port 9001.

yes, the docker image starts a fuzzing server which can be used with testee client

https://github.com/crossbario/autobahn-testsuite/blob/09cfbf74b0c8e335c6fc7df88e5c88349ca66879/docker/Dockerfile#L41

> How can I test my websocket server running on port 8080 ?

log in to the running container an use `wstest --mode fuzzingclient` with an appropriate config like

https://github.com/crossbario/autobahn-testsuite/blob/master/docker/config/fuzzingclient.json

you only need 1 server with your desired port here
