### ISSUE TITLE
Run specific testcase?

### ISSUE THREAD

**Issue by Pithikos** [tavendo/AutobahnTestSuite#46]
I appreciate the work done for this tessuite. I use it to debug a websocket server I built. The problem is that there are many test cases and I want to narrow down the debugging to specific test cases. For example if the problem is on test case *9.2.3* I don't want to have to wait for all the tests for every attempt to fix my bug.

So is there a way to run a specific testcase? 

Examples:
````
wstest --mode fuzzingclient --testcase 9.2.3
wstest --mode fuzzingclient --testcase 7-9 # this would run all test cases from 7.x.x to 9.x.x
````

**Comment by zaphoyd** [comment]
Take a look at the fuzzingclient.json and fuzzingserver.json config files. They allow you to specific a single test or a sub-range, exclude a specific test or subrange, etc.

**Comment by oberstet** [comment]
Exactly. You can use patterns like `"cases": ["1.*", "3.1.*"]` in the config https://github.com/tavendo/AutobahnTestSuite/blob/master/examples/fuzzingserver/fuzzingserver.json#L8

**Comment by Pithikos** [comment]
Thank you. It wasn't that clear for a newbie how to go on doing this but now I figured it out :)

For future reference, you simply have the json in the same directory where you run wstest:
````
wstest --mode fuzzingclient --testset fuzzingclient.json
````

fuzzingclient.json:
````
{
   "options": {"failByDrop": false},
   "outdir": "./reports/servers",

   "servers": [{"agent": "AutobahnServer", "url": "ws://localhost:9001", "options": {"version": 18}}],

   "cases": ["9.*"],
   "exclude-cases": [],
   "exclude-agent-cases": {}
}
````

The above configuration will run all 9.x.x tests.
