### ISSUE TITLE
Strange fuzzingclient test closing behavior in 6.4.3 and 6.4.4

### ISSUE THREAD

**Issue by jrudolph** [tavendo/AutobahnTestSuite#47]
In those tests, the testsuite client sends a close frame while in the middle of another frame. A server cannot possibly read this close frame properly (because it cannot be expecting it). It isn't really relevant to the test semantics because the client sent invalid UTF-8 data before so what the test checks is that the server will timeout the connection after a while. 

As the test case description doesn't mention this behavior it is confusing when trying to fix an implementation that fails at this test case.

**Comment by oberstet** [comment]
No, it doesn't send a close frame, but invalid UTF8 http://autobahn.ws/testsuite/reports_20140823/servers/index.html#case_desc_6_4_3

**Comment by jrudolph** [comment]
Yes, it first sends invalid UTF8 but as soon as the server sends a close frame it tries to answer with its own close frame which it shouldn't try to do without finishing the unfinished previous frame. 

Here's the log from a 6.4.3 run:
```
000 TX OCTETS: 474554202f20485454502f312e310d0a557365722d4167656e743a204175746f6261686e5465737453756974652f302e372e
               312d302e31302e300d0a486f7374 ...
001 RX OCTETS: 485454502f312e312031303120537769746368696e672050726f746f636f6c730d0a557067726164653a20776562736f636b
               65740d0a5365632d576562536f63 ...
002 TX OCTETS: 0195b209a859 // text frame, mask flag, length 0x15 = 21 bytes, mask
003 TX OCTETS: 7cb349e40bc62b970ec71d // 11 masked data bytes (10 remaining in frame)
004 DELAY 1.000000 sec for TAG A
005 RX OCTETS: 0100
006 RX FRAME : OPCODE=1, FIN=False, RSV=0, PAYLOAD-LEN=0, MASKED=False, MASK=None
007 RX OCTETS: 000bcebae1bdb9cf83cebcceb5
008 RX FRAME : OPCODE=0, FIN=False, RSV=0, PAYLOAD-LEN=11, MASKED=False, MASK=None
               κόσμε
009 DELAY TIMEOUT on TAG A
010 TX OCTETS: ad228928 // 4 masked data bytes (6 remaining)
011 DELAY 1.000000 sec for TAG B
012 RX OCTETS: 880203ef
013 RX FRAME : OPCODE=8, FIN=True, RSV=0, PAYLOAD-LEN=2, MASKED=False, MASK=None
               0x03ef
014 TX FRAME : OPCODE=8, FIN=True, RSV=0, PAYLOAD-LEN=2, MASK=7b79bd7f, PAYLOAD-REPEAT-LEN=None, CHOPSIZE=None, SYNC=False
               0x03e8
015 TX OCTETS: 88827b79bd7f7891 // will be interpreted as remaining 6 bytes + extra data
016 DELAY TIMEOUT on TAG B
017 TCP DROPPED BY PEER
```

**Comment by jrudolph** [comment]
ping
